# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1056, 687)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setStyleSheet("QFrame{background-color:#1a1a1e;\n"
"border:none;\n"
"border-radius:12px;\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame.sizePolicy().hasHeightForWidth())
        self.left_frame.setSizePolicy(sizePolicy)
        self.left_frame.setMinimumSize(QtCore.QSize(250, 0))
        self.left_frame.setStyleSheet("QFrame{background-color:#1f1f22;\n"
"border:none;\n"
"border-radius:12px;\n"
"}")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.search_frame = QtWidgets.QFrame(self.left_frame)
        self.search_frame.setMinimumSize(QtCore.QSize(0, 52))
        self.search_frame.setMaximumSize(QtCore.QSize(16777215, 52))
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_left_frame = QtWidgets.QFrame(self.search_frame)
        self.search_left_frame.setMinimumSize(QtCore.QSize(0, 52))
        self.search_left_frame.setMaximumSize(QtCore.QSize(16777215, 52))
        self.search_left_frame.setStyleSheet("background-color: #2a2a2d;\n"
"border-radius: 12px;")
        self.search_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_left_frame.setObjectName("search_left_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.search_left_frame)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.search_btn = QtWidgets.QPushButton(self.search_left_frame)
        self.search_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.search_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn.setStyleSheet("QPushButton {\n"
"\n"
"border: none; /* 边框样式 */\n"
"\n"
"}\n"
"\n"
"/* 设置PushButton在鼠标悬停状态下的样式 */\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"\n"
"/* 设置PushButton在鼠标按下状态下的样式 */\n"
"QPushButton:pressed {\n"
"   border: 1px solid rgba(53, 53, 53,00);\n"
"\n"
"}\n"
"\n"
"/* 设置PushButton在不可用状态下的样式 */\n"
"QPushButton:disabled {\n"
"    background-color: #D3D3D3; /* 不可用状态的背景颜色 */\n"
"    color: #808080; /* 不可用状态的文字颜色 */\n"
"}")
        self.search_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/搜索.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon)
        self.search_btn.setIconSize(QtCore.QSize(18, 18))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_5.addWidget(self.search_btn)
        self.search_line = QtWidgets.QLineEdit(self.search_left_frame)
        self.search_line.setMinimumSize(QtCore.QSize(0, 42))
        self.search_line.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_line.setStyleSheet("font-family:\"微软雅黑\";\n"
"color:white;")
        self.search_line.setReadOnly(False)
        self.search_line.setObjectName("search_line")
        self.horizontalLayout_5.addWidget(self.search_line)
        self.horizontalLayout_3.addWidget(self.search_left_frame)
        self.add_btn = QtWidgets.QPushButton(self.search_frame)
        self.add_btn.setMinimumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(113, 109, 252), stop:1 rgb(164, 124, 255));\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"      text-align: center center;\n"
"} ")
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.verticalLayout.addWidget(self.search_frame)
        self.session_list = QtWidgets.QListWidget(self.left_frame)
        self.session_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.session_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.session_list.setObjectName("session_list")
        self.verticalLayout.addWidget(self.session_list)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(self.main_frame)
        self.right_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.right_frame)
        self.frame.setMinimumSize(QtCore.QSize(200, 150))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 25, 100, 100))
        self.label.setStyleSheet("image:url(:/resources/avatar_5.png);\n"
"background-repeat: no-repeat;  /* 防止图片重复 */\n"
"background-position: center;   /* 图片居中显示 */\n"
"background-size: cover;        /* 使图片覆盖整个 QFrame */")
        self.label.setText("")
        self.label.setObjectName("label")
        self.name_label = QtWidgets.QLabel(self.frame)
        self.name_label.setGeometry(QtCore.QRect(170, 40, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color:white;")
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.frame)
        self.chat_list = QtWidgets.QListWidget(self.right_frame)
        self.chat_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_list.setObjectName("chat_list")
        self.verticalLayout_2.addWidget(self.chat_list)
        self.input_frame = QtWidgets.QFrame(self.right_frame)
        self.input_frame.setMinimumSize(QtCore.QSize(0, 56))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 56))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.input_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_left_frame = QtWidgets.QFrame(self.input_frame)
        self.input_left_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.input_left_frame.setMaximumSize(QtCore.QSize(16777215, 56))
        self.input_left_frame.setStyleSheet("background-color: #2a2a2d;\n"
"border-radius: 12px;")
        self.input_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_left_frame.setObjectName("input_left_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.input_left_frame)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.input_line = QtWidgets.QPlainTextEdit(self.input_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_line.sizePolicy().hasHeightForWidth())
        self.input_line.setSizePolicy(sizePolicy)
        self.input_line.setMinimumSize(QtCore.QSize(0, 56))
        self.input_line.setMaximumSize(QtCore.QSize(16777215, 56))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        self.input_line.setFont(font)
        self.input_line.setStyleSheet("color:white;")
        self.input_line.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_line.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_line.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.input_line.setObjectName("input_line")
        self.horizontalLayout_6.addWidget(self.input_line)
        self.horizontalLayout_4.addWidget(self.input_left_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.send_btn = QtWidgets.QPushButton(self.input_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        self.send_btn.setFont(font)
        self.send_btn.setStyleSheet("QPushButton{\n"
"    image: url(:/resources/发送.png);\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(113, 109, 252), stop:1 rgb(164, 124, 255));\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"      text-align: center center;\n"
"} ")
        self.send_btn.setText("")
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_4.addWidget(self.send_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.input_frame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.right_frame)
        self.horizontalLayout.addWidget(self.main_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search_btn.setToolTip(_translate("Form", "打开音乐库"))
        self.search_line.setPlaceholderText(_translate("Form", "add new"))
        self.add_btn.setText(_translate("Form", "+"))
import res_rc
