# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1800, 1200)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(90, -70, 101, 1241))
        self.frame.setStyleSheet("image:url(:/resources/ver_line.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.input_frame = QtWidgets.QFrame(Form)
        self.input_frame.setGeometry(QtCore.QRect(220, 420, 764, 56))
        self.input_frame.setMinimumSize(QtCore.QSize(0, 56))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 58))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.input_left_frame = QtWidgets.QFrame(self.input_frame)
        self.input_left_frame.setGeometry(QtCore.QRect(1, 1, 718, 54))
        self.input_left_frame.setMinimumSize(QtCore.QSize(0, 42))
        self.input_left_frame.setMaximumSize(QtCore.QSize(16777215, 58))
        self.input_left_frame.setStyleSheet("")
        self.input_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_left_frame.setObjectName("input_left_frame")
        self.send_btn = QtWidgets.QPushButton(self.input_left_frame)
        self.send_btn.setGeometry(QtCore.QRect(537, 0, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setMinimumSize(QtCore.QSize(40, 51))
        font = QtGui.QFont()
        font.setFamily("Californian FB")
        font.setPointSize(12)
        self.send_btn.setFont(font)
        self.send_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(113, 109, 252), stop:1 rgb(164, 124, 255));\n"
"    \n"
"    border-radius:6px;\n"
"      text-align: center center;\n"
"} ")
        self.send_btn.setObjectName("send_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.input_left_frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 0, 541, 51))
        self.lineEdit.setStyleSheet("border-radius:6px;\n"
"text-align: center center;\n"
"background-color:white;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.raise_()
        self.send_btn.raise_()
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 1080, 671, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(1330, 80, 381, 521))
        self.frame_2.setStyleSheet("background-image:url(:/resources/background-image.png);\n"
" background-repeat: no-repeat;  /* 防止图片重复 */\n"
"                background-position: center;   /* 图片居中显示 */\n"
"                background-size: cover;        /* 使图片覆盖整个 QFrame */")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(260, 640, 261, 251))
        self.frame_3.setStyleSheet("background-color:rgba(80,80,80,50);\n"
"border:none;\n"
"border-radius:12px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"background-color:rgba(0,0,0,0);")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(80, 120, 91, 91))
        self.label_6.setStyleSheet("background-color:ragb(0,0,0,0);\n"
"background-image:url(:/resources/search.png);\n"
" background-repeat: no-repeat;  /* 防止图片重复 */\n"
"                background-position: center;   /* 图片居中显示 */\n"
"                background-size: cover;        /* 使图片覆盖整个 QFrame */")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(560, 640, 261, 251))
        self.frame_4.setStyleSheet("background-color:rgba(80,80,80,50);\n"
"border:none;\n"
"border-radius:12px;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"background-color:rgba(0,0,0,0);")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(80, 120, 91, 91))
        self.label_7.setStyleSheet("background-color:ragb(0,0,0,0);\n"
"background-image:url(:/resources/recommendation.png);\n"
" background-repeat: no-repeat;  /* 防止图片重复 */\n"
"                background-position: center;   /* 图片居中显示 */\n"
"                background-size: cover;        /* 使图片覆盖整个 QFrame */")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(860, 640, 261, 251))
        self.frame_5.setStyleSheet("background-color:rgba(80,80,80,50);\n"
"border:none;\n"
"border-radius:12px;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color:rgba(0,0,0,0);")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(90, 120, 91, 91))
        self.label_8.setStyleSheet("background-color:ragb(0,0,0,0);\n"
"background-image:url(:/resources/summary.png);\n"
" background-repeat: no-repeat;  /* 防止图片重复 */\n"
"                background-position: center;   /* 图片居中显示 */\n"
"                background-size: cover;        /* 使图片覆盖整个 QFrame */")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(240, 90, 1041, 161))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white")
        self.label_5.setObjectName("label_5")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 1800, 1200))
        self.main_frame.setStyleSheet("background-color:#0e1116;\n"
"border:none;\n"
"border-radius:12px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.main_frame.raise_()
        self.frame.raise_()
        self.input_frame.raise_()
        self.label.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.label_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.send_btn.setText(_translate("Form", "Sign in"))
        self.lineEdit.setPlaceholderText(_translate("Form", "please input youar partner name"))
        self.label.setText(_translate("Form", "Code Bot"))
        self.label_2.setText(_translate("Form", "Search"))
        self.label_3.setText(_translate("Form", "Chat"))
        self.label_4.setText(_translate("Form", "Summary"))
        self.label_5.setText(_translate("Form", "Your best code copilot!"))
import res_rc
